apiVersion: v1
kind: Service
metadata:
  name: my-k8s-service
spec:
  type: NodePort
  selector:
    app: my-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
